name: CI
on: [push]
jobs:
  native_test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.2']
        elixir: ['1.13.2']
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      MIX_TEST_PARTITION: 5
    steps:
      - uses: erlef/setup-beam@v1.8
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/checkout@v2
      - run: mix deps.get
      - run: mix compile
      - run: mix dialyzer
      - run: mix test native_test
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['23.3.4.10', '24.2']
        elixir: [1.12.3', '1.13.2']
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      MIX_TEST_PARTITION: 5
    steps:
      - uses: erlef/setup-beam@v1.8
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/checkout@v2
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile
      - run: mix test test